---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - application.wsb.edu.pl
  resources:
  - weatherapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - application.wsb.edu.pl
  resources:
  - weatherapps/finalizers
  verbs:
  - update
- apiGroups:
  - application.wsb.edu.pl
  resources:
  - weatherapps/status
  verbs:
  - get
  - patch
  - update
