# permissions for end users to view weatherapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: declarative-weather
    app.kubernetes.io/managed-by: kustomize
  name: weatherapp-viewer-role
rules:
- apiGroups:
  - application.wsb.edu.pl
  resources:
  - weatherapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - application.wsb.edu.pl
  resources:
  - weatherapps/status
  verbs:
  - get
